config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'sessions/create'

  get 'sessions/destroy'

  resources :items
  resources :customers
  resources :employees
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  

  root 'welcome#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customers
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  
  helper_method :get_primary_key_controller
  def get_primary_key_controller(ord)
    ord.get_primary_key_model
  end

  # GET /orders
  # GET /orders.json
  def index
    if isEmployee?
      @orders = Order.all
    
    elsif isCustomer?
      customer = Customer.find_by email_address: current_user.email_address
      @orders = customer.orders
      
    else
      @orders = []
    end
      
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    item = Item.find_by item_id: @order.item_id

    respond_to do |format|
      if (item == nil)
          format.html { redirect_to items_url, notice: 'You entered an invalid item ID. The following are available:' }
      elsif @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
        
        # set other things if correct
        @order.order_id = @order.id
        @order.item_name = item.name
        @order.cost = (item.cost) * (@order.quantity)
        @order.status = "new"
        @order.placed_at = Time.now
        
        if isCustomer?
          customer = Customer.find_by email_address: current_user.email_address
          @order.customer_id = customer.id
        end
        
        @order.save
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:order_id, :customer_id, :item_id, :quantity,:placed_at, :status)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <% if isEmployee? %>
    <div class="field">
      <%= f.label :status %><br>
      <%= f.select :status, [['Delievered','Delievered'],['Cancelled','Cancelled'],['Pending','Pending']] %>
    </div>
  
  <% else %>
    <div class="field">
      <%= f.label :item_id %><br>
      <%= f.number_field :item_id %>
    </div>

    <div class="field">
      <%= f.label :quantity %><br>
      <%= f.number_field :quantity %>
    </div>
    
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
  
<% end %>

app/views/orders/edit.html.erb
<div id="editOrderDiv">
    <h1>Edit this order</h1>

    <%= render 'form' %>
    
    <%= link_to 'Show', @order %> |
    <%= link_to 'Back', orders_path %>
</div>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<div id="allOrdersDiv">

  <h1>All Orders</h1>
  <table>
    <thead>
      <tr>
        <th>Order ID</th>
        <% if isEmployee? %>
        <th>Customer ID</th>
        <% end %>
        <th>Item ID</th>
        <th>Item Name</th>
        <th>Quantity</th>
        <th>Total Cost</th>
        <th>Placed at</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody class="tblVals">
      <% @orders.each do |order| %>
        <tr>
          <td align="center"><%= order.order_id %></td>
          <% if isEmployee? %>
            <td align="center"><%= order.customer_id %></td>
          <% end %>
          <td align="center"><%= order.item_id %></td>
          <td align="center"><%= order.item_name %></td>
          <td align="center"><%= order.quantity %></td>
          <td align="center"><%= order.cost %></td>
          <td align="center"><%= order.placed_at %></td>
          <td align="center"><%= order.status %></td>
          <td align="center"><%= link_to 'Show', order %></td>
          <!--<td><%= link_to 'Edit', edit_order_path(order) %></td>-->
          <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <% if not isEmployee? %>
    <%= link_to 'New Order', new_order_path %>
  <% end %>
</div>

app/views/orders/new.html.erb
<div id="newOrderDiv">
    <h1>Place a new Order</h1>
    
    <%= render 'form' %>
    
    <%= link_to 'View Items', items_path %>
    <%= link_to 'Back', orders_path %>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<div id="dspOrderDiv">
  <p>
    <strong>Order:</strong>
    <%= @order.order_id %>
  </p>
  
  <p>
    <strong>Customer:</strong>
    <%= @order.customer_id %>
  </p>
  
  <p>
    <strong>Item ID:</strong>
    <%= @order.item_id %>
  </p>

  <p>
    <strong>Item Name:</strong>
    <%= @order.item_name %>
  </p>
  
  <p>
    <strong>Quantity:</strong>
    <%= @order.quantity %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= @order.cost %>
  </p>
  
  <p>
    <strong>Placed at:</strong>
    <%= @order.placed_at %>
  </p>
  
  <p>
    <strong>Status:</strong>
    <%= @order.status %>
  </p>


<% if isEmployee? %>
  <%= link_to 'Process', edit_order_path(@order) %> |
<% else %>
  <%= link_to 'Edit', edit_order_path(@order) %> |
<% end %>
  
<%= link_to 'Back', orders_path %>

</div>